_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/region

NAME: globalise

PREPROCESS:
  REGION:
    REGIONS: ["paragraph", "signature-mark", "catch-word", "page-number",
              "header", "heading", "marginalia"]
    MERGE_REGIONS: ["paragraph:heading"]
    REGION_TYPE: []

MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 7

  ROI_HEADS:
    NUM_CLASSES: 6
  
  WEIGHTS: 

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: pretrained_models/region_model_best_mIoU.pth

