_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/separator

MODEL:
  MODE: separator

  SEM_SEG_HEAD:
    NUM_CLASSES: 2
  
  WEIGHTS: 

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: pretrained_models/separator_model_best_mIoU.pth
