_BASE_: ../panoptic_base.yaml

OUTPUT_DIR: ./output/region

NAME: region_pano

MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 7
  ROI_HEADS:
    NUM_CLASSES: 6
  
  WEIGHTS: 

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: 
#   EVAL_PERIOD: 100

# SOLVER:
#   IMS_PER_BATCH: 4
#   CHECKPOINT_PERIOD: 250
#   BASE_LR: 0.002
#   STEPS: (800, 1200, 1600)
#   MAX_ITER: 2500

