_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/end

MODEL:
  MODE: end

  SEM_SEG_HEAD:
    NUM_CLASSES: 2
  
  WEIGHTS: 

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS: pretrained_models/region_model_best_mIoU.pth

